
import React from 'react';

export const BRAZILIAN_STATES = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Roraima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' }
];

export const BANKS = [
  { code: '001', name: 'Banco do Brasil S.A.' },
  { code: '033', name: 'Banco Santander (Brasil) S.A.' },
  { code: '104', name: 'Caixa Econômica Federal' },
  { code: '237', name: 'Banco Bradesco S.A.' },
  { code: '341', name: 'Itaú Unibanco S.A.' },
  { code: '041', name: 'Banco do Estado do Rio Grande do Sul S.A. (Banrisul)' },
  { code: '077', name: 'Banco Inter S.A.' },
  { code: '260', name: 'Nu Pagamentos S.A. (Nubank)' },
  { code: '290', name: 'PagSeguro Internet S.A. (PagBank)' },
  { code: '336', name: 'Banco C6 S.A.' },
  { code: '389', name: 'Banco Mercantil do Brasil S.A.' },
  { code: '422', name: 'Banco Safra S.A.' },
  { code: '633', name: 'Banco Rendimento S.A.' },
  { code: '655', name: 'Banco Votorantim S.A.' },
  { code: '707', name: 'Banco Daycoval S.A.' },
  { code: '745', name: 'Banco Citibank S.A.' },
  { code: '748', name: 'Banco Cooperativo Sicredi S.A.' },
  { code: '756', name: 'Banco Cooperativo do Brasil S.A. (Bancoob/Sicoob)' }
];

export const TRANSLATIONS = {
  'en': {
    management: 'SCP Management Dashboard',
    welcome: 'Welcome back,',
    missedYou: 'We missed you.',
    dashboard: 'Dashboard',
    scpInfo: 'SCP Information',
    headSession: 'HEAD',
    executives: 'Executives',
    clients: 'Clients',
    investments: 'Investments',
    contracts: 'Contracts',
    walletParticipation: 'PARTICIPATION WALLET',
    walletIndividual: 'INDIVIDUAL WALLET',
    walletInherited: 'INHERITED WALLET',
    maskedButton: 'View Data',
    help: 'Help',
    addInfo: 'Add Information',
    search: 'Search',
    status: 'Status',
    type: 'Type',
    actions: 'Actions',
    bankData: 'Banking Data',
    address: 'Address',
    documents: 'Documents',
    general: 'General',
    register: 'REGISTER',
    createContract: 'Create Contract',
    pf: 'Individual',
    pj: 'Legal Entity',
    logout: 'Logout',
    profile: 'Profile',
    financial: 'Financial',
    name: 'Name',
    document: 'Document',
    consultant: 'Consultant',
    amount: 'Amount',
    rate: 'Rate',
    months: 'Months',
    startDate: 'Start Date',
    endDate: 'End Date',
    client: 'Client',
    number: 'Number',
    active: 'Active',
    pending: 'Pending',
    unfit: 'Unfit',
    fit: 'Fit',
    role: 'Role',
    email: 'E-mail',
    phone: 'Phone/WhatsApp',
    fullName: 'Full Name',
    birthDate: 'Birth Date',
    zipCode: 'ZIP Code',
    street: 'Street',
    neighborhood: 'Neighborhood',
    city: 'City',
    state: 'State',
    bank: 'Bank',
    agency: 'Agency',
    account: 'Account',
    digit: 'Digit',
    pixSection: 'Pix Section',
    pixType: 'Pix Key Type',
    pixKey: 'Pix Key',
    cancel: 'Cancel',
    save: 'Save Changes',
    restrictedAccess: 'Restricted Access',
    notAvailable: 'This tab is not available for your profile.',
    companyName: 'Company Name',
    cnpj: 'CNPJ',
    businessName: 'Business Name',
    monthlyEvolution: 'Monthly Evolution',
    recentActivity: 'Recent Activities',
    statusFlow: 'Status',
    analysis: 'Analysis',
    password: 'Password',
    onboarding: 'Onboarding',
    registered: 'Registered',
    assignedLeader: 'Assign Leader',
    searchExec: 'Search Executive',
    placeholderSearch: 'Ex: Search here...',
    generateEdition: 'Generate Magic Edition',
    aiThinking: 'Gemini is thinking...',
    noResult: 'No results generated yet',
    monthsNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    daysShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
  },
  'es': {
    management: 'Gestión SCP',
    welcome: 'Bienvenido de nuevo,',
    missedYou: 'Te extrañamos.',
    dashboard: 'Panel de Control',
    scpInfo: 'Información SCP',
    headSession: 'HEAD',
    executives: 'Ejecutivos',
    clients: 'Clientes',
    investments: 'Inversiones',
    contracts: 'Contratos',
    walletParticipation: 'CARTERA DE PARTICIPACIÓN',
    walletIndividual: 'CARTERA INDIVIDUAL',
    walletInherited: 'CARTERA HEREDADA',
    maskedButton: 'Ver Datos',
    help: 'Ayuda',
    addInfo: 'Agregar Información',
    search: 'Buscar',
    status: 'Estado',
    type: 'Tipo',
    actions: 'Acciones',
    bankData: 'Datos Bancarios',
    address: 'Dirección',
    documents: 'Documentos',
    general: 'General',
    register: 'REGISTRAR',
    createContract: 'Crear Contrato',
    pf: 'Persona Física',
    pj: 'Persona Jurídica',
    logout: 'Cerrar Sesión',
    profile: 'Perfil',
    financial: 'Financiero',
    name: 'Nombre',
    document: 'Documento',
    consultant: 'Consultor',
    amount: 'Monto',
    rate: 'Tasa',
    months: 'Meses',
    startDate: 'Fecha Inicio',
    endDate: 'Fecha Fin',
    client: 'Cliente',
    number: 'Número',
    active: 'Activo',
    pending: 'Pendiente',
    unfit: 'No Apto',
    fit: 'Apto',
    role: 'Cargo',
    email: 'Correo electrónico',
    phone: 'Teléfono/WhatsApp',
    fullName: 'Nombre Completo',
    birthDate: 'Fecha Nacimiento',
    zipCode: 'Código Postal',
    street: 'Dirección',
    neighborhood: 'Barrio',
    city: 'Ciudad',
    state: 'Estado',
    bank: 'Banco',
    agency: 'Agencia',
    account: 'Cuenta',
    digit: 'Dígito',
    pixSection: 'Sección Pix',
    pixType: 'Tipo de Clave',
    pixKey: 'Clave Pix',
    cancel: 'Cancelar',
    save: 'Guardar Cambios',
    restrictedAccess: 'Acceso Restringido',
    notAvailable: 'Esta pestaña no está disponible para su perfil.',
    companyName: 'Nombre Fantasía',
    cnpj: 'CNPJ/RUT',
    businessName: 'Razón Social',
    monthlyEvolution: 'Evolución Mensual',
    recentActivity: 'Actividades Recientes',
    statusFlow: 'Estado',
    analysis: 'Análisis',
    password: 'Contraseña',
    onboarding: 'Incorporación',
    registered: 'Registrado',
    assignedLeader: 'Asignar Líder',
    searchExec: 'Buscar Ejecutivo',
    placeholderSearch: 'Ex: Buscar aquí...',
    generateEdition: 'Generar Edición Mágica',
    aiThinking: 'Gemini está pensando...',
    noResult: 'Ningún resultado generado todavía',
    monthsNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Setembre', 'Octubre', 'Noviembre', 'Diciembre'],
    daysShort: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá']
  },
  'pt-br': {
    management: 'Gerenciador SCP',
    welcome: 'Bem vindo de volta,',
    missedYou: 'Sentimos sua falta.',
    dashboard: 'Dashboard',
    scpInfo: 'Informações SCP',
    headSession: 'HEAD',
    executives: 'Executivos',
    clients: 'Clientes',
    investments: 'Investimentos',
    contracts: 'Contratos',
    walletParticipation: 'CARTEIRA DE PARTICIPAÇÃO',
    walletIndividual: 'CARTEIRA INDIVIDUAL',
    walletInherited: 'CARTEIRA HERDADA',
    maskedButton: 'Visualizar Dados',
    help: 'Ajuda',
    addInfo: 'Adicionar Informação',
    search: 'Pesquisar',
    status: 'Status',
    type: 'Tipo',
    actions: 'Ações',
    bankData: 'Bancários',
    address: 'Endereço',
    documents: 'Documentos',
    general: 'Gerais',
    register: 'CADASTRAR',
    createContract: 'Criar novo contrato',
    pf: 'Pessoa Física',
    pj: 'Pessoa Jurídica',
    logout: 'Sair',
    profile: 'Perfil',
    financial: 'Financeiro',
    name: 'Nome',
    document: 'Documento',
    consultant: 'Consultor',
    amount: 'Valor Aporte',
    rate: 'Taxa',
    months: 'Meses',
    startDate: 'Data Início',
    endDate: 'Data Fim',
    client: 'Cliente',
    number: 'Número',
    active: 'Ativo',
    pending: 'Pendente',
    unfit: 'Não Apto',
    fit: 'Apto',
    role: 'Cargo',
    email: 'E-mail',
    phone: 'Telefone/Whats',
    fullName: 'Nome Completo',
    birthDate: 'Nascimento',
    zipCode: 'CEP',
    street: 'Logradouro',
    neighborhood: 'Bairro',
    city: 'Cidade',
    state: 'Estado',
    bank: 'Banco',
    agency: 'Agência',
    account: 'Conta',
    digit: 'Dígito',
    pixSection: 'Seção Pix',
    pixType: 'Tipo da Chave',
    pixKey: 'Chave Pix',
    cancel: 'Cancelar',
    save: 'SALVAR ALTERAÇÕES',
    restrictedAccess: 'Acesso Restrito',
    notAvailable: 'A guia SCP não está disponível para o seu perfil.',
    companyName: 'Nome Fantasia',
    cnpj: 'CNPJ',
    businessName: 'Razão Social',
    monthlyEvolution: 'Evolução Mensal',
    recentActivity: 'Últimas Atividades',
    statusFlow: 'Status',
    analysis: 'Análise',
    password: 'Senha',
    onboarding: 'Onboarding',
    registered: 'Cadastrado',
    assignedLeader: 'Atribuir Líder',
    searchExec: 'Pesquisar Executivo',
    placeholderSearch: 'Ex: Pesquise aqui...',
    generateEdition: 'Gerar Edição Mágica',
    aiThinking: 'Gemini está pensando...',
    noResult: 'Nenhum resultado gerado ainda',
    monthsNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    daysShort: ['Do', 'Se', 'Te', 'Qu', 'Qu', 'Se', 'Sá']
  }
};
