-- Criação da tabela bank_accounts
CREATE TABLE IF NOT EXISTS public.bank_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Tipo de registro: 1 = Conta, 2 = Pix
    account_type int NOT NULL CHECK (account_type IN (1, 2)),
    is_valid boolean NOT NULL DEFAULT true,
    is_primary boolean NOT NULL DEFAULT false,

    -- Dados do banco
    bank_id char(3) NOT NULL, -- exemplo: 001 = Banco do Brasil
    bank_name text NOT NULL, -- nome do banco (opcional, para legibilidade)
    
    -- Campos para conta tradicional
    agency varchar(10),
    account varchar(20),
    digit varchar(2),
    account_kind int CHECK (account_kind IS NULL OR account_kind IN (1,2,3)), -- enum: 1=corrente,2=poupanca,3=conjunta
    account_holder text,
    
    -- Campos para Pix
    pix_key_type int CHECK (pix_key_type IS NULL OR pix_key_type IN (1,2,3,4)), -- enum de 4 tipos
    pix_key varchar(255),
    
    -- Vinculação
    customer_id bigint NULL REFERENCES public.customers(id),
    executive_id bigint NULL REFERENCES public.executives(id),
    
    -- Checks para garantir consistência
    CONSTRAINT bank_accounts_account_fields_check CHECK (
        (account_type = 1 AND agency IS NOT NULL AND account IS NOT NULL AND digit IS NOT NULL AND account_kind IS NOT NULL AND account_holder IS NOT NULL)
        OR
        (account_type = 2 AND pix_key_type IS NOT NULL AND pix_key IS NOT NULL)
    ),
    
    -- Opcional: garantir que só esteja vinculado a cliente ou executivo
    CONSTRAINT bank_accounts_owner_check CHECK (
        (customer_id IS NOT NULL AND executive_id IS NULL)
        OR
        (customer_id IS NULL AND executive_id IS NOT NULL)
    )
);

-- Comentários
COMMENT ON COLUMN public.bank_accounts.account_type IS '1=Conta, 2=Pix';
COMMENT ON COLUMN public.bank_accounts.bank_id IS 'Código do banco, 3 dígitos';
COMMENT ON COLUMN public.bank_accounts.bank_name IS 'Nome do banco';
COMMENT ON COLUMN public.bank_accounts.agency IS 'Agência da conta';
COMMENT ON COLUMN public.bank_accounts.account IS 'Número da conta';
COMMENT ON COLUMN public.bank_accounts.digit IS 'Dígito da conta';
COMMENT ON COLUMN public.bank_accounts.account_kind IS 'Tipo da conta: 1=corrente,2=poupança,3=conjunta';
COMMENT ON COLUMN public.bank_accounts.account_holder IS 'Nome do titular da conta';
COMMENT ON COLUMN public.bank_accounts.pix_key_type IS 'Tipo da chave Pix, enum de 4 tipos';
COMMENT ON COLUMN public.bank_accounts.pix_key IS 'Chave Pix';
COMMENT ON COLUMN public.bank_accounts.customer_id IS 'Vinculado a cliente';
COMMENT ON COLUMN public.bank_accounts.executive_id IS 'Vinculado a executivo';
COMMENT ON COLUMN public.bank_accounts.is_valid IS 'Indica se a conta/pix é válida (true=valid, false=invalid)';
COMMENT ON COLUMN public.bank_accounts.is_primary IS 'Indica se esta é a conta principal/selecionada do cliente ou executivo';

-- Habilitar Row Level Security
ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;

-- Índices recomendados
CREATE INDEX idx_bank_accounts_customer_id ON public.bank_accounts(customer_id);
CREATE INDEX idx_bank_accounts_executive_id ON public.bank_accounts(executive_id);
CREATE INDEX idx_bank_accounts_pix_key ON public.bank_accounts(pix_key);
CREATE UNIQUE INDEX uniq_primary_customer_account
ON public.bank_accounts(customer_id)
WHERE is_primary = true AND customer_id IS NOT NULL;
CREATE UNIQUE INDEX uniq_primary_executive_account
ON public.bank_accounts(executive_id)
WHERE is_primary = true AND executive_id IS NOT NULL;

