-- Criação da tabela customers
CREATE TABLE IF NOT EXISTS public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Tipo de cliente: PF = Pessoa Física, PJ = Pessoa Jurídica
    customer_type char(2) NOT NULL CHECK (customer_type IN ('PF','PJ')),
    
    register_date timestamp with time zone DEFAULT timezone('utc'::text, now()),
    
    -- Pessoa Física
    full_name text,
    cpf varchar(11),
    marital_status int,
    rg varchar(10),
    birth_place text,
    birth_date date,
    email text UNIQUE,
    
    -- Pessoa Jurídica
    company_name text,
    trade_name text,
    cnpj varchar(14),
    representative_name text,
    job_title text,
    
    -- Contato
    phone varchar(15),
    whatsapp varchar(15),
    
    -- Endereço
    postal_code varchar(8),
    street text,
    address_number text,
    neighborhood text,
    city text,
    state int,
    country char(2) DEFAULT 'BR',
    
    -- Restrições (Checks)
    -- Utilizamos 'IS NULL OR' para permitir que campos opcionais fiquem vazios sem violar a regra
    CONSTRAINT customers_cpf_check CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$'),
    CONSTRAINT customers_cnpj_check CHECK (cnpj IS NULL OR cnpj ~ '^[0-9]{14}$'),
    CONSTRAINT customers_phone_check CHECK (phone IS NULL OR phone ~ '^[0-9]{10,13}$'),
    CONSTRAINT customers_whatsapp_check CHECK (whatsapp IS NULL OR whatsapp ~ '^[0-9]{10,13}$'),
    CONSTRAINT customers_postal_code_check CHECK (postal_code IS NULL OR postal_code ~ '^[0-9]{8}$'),
    CONSTRAINT customers_marital_status_check CHECK (marital_status IS NULL OR marital_status IN (1, 2, 3, 4, 5)),
    CONSTRAINT customers_state_check CHECK (state IS NULL OR (state >= 1 AND state <= 27)),
    
    -- Unique opcional (CPF ou CNPJ)
    CONSTRAINT customers_cpf_unique UNIQUE (cpf),
    CONSTRAINT customers_cnpj_unique UNIQUE (cnpj)
);

-- Comentários úteis para documentação no Supabase
COMMENT ON COLUMN public.customers.customer_type IS 'PF = Pessoa Física, PJ = Pessoa Jurídica';
COMMENT ON COLUMN public.customers.full_name IS 'Nome completo da pessoa física';
COMMENT ON COLUMN public.customers.cpf IS 'CPF da pessoa física, apenas números, único mas opcional';
COMMENT ON COLUMN public.customers.marital_status IS 'Estado civil da pessoa física, controlado pelo sistema';
COMMENT ON COLUMN public.customers.birth_place IS 'Naturalidade da pessoa física';
COMMENT ON COLUMN public.customers.birth_date IS 'Data de nascimento da pessoa física';
COMMENT ON COLUMN public.customers.email IS 'Email do cliente, único';
COMMENT ON COLUMN public.customers.company_name IS 'Razão social da empresa';
COMMENT ON COLUMN public.customers.trade_name IS 'Nome fantasia da empresa';
COMMENT ON COLUMN public.customers.cnpj IS 'CNPJ da empresa, apenas números, único mas opcional';
COMMENT ON COLUMN public.customers.representative_name IS 'Nome do representante da empresa';
COMMENT ON COLUMN public.customers.job_title IS 'Profissão ou cargo do representante da empresa';
COMMENT ON COLUMN public.customers.phone IS 'Telefone fixo ou celular';
COMMENT ON COLUMN public.customers.whatsapp IS 'Número de WhatsApp';
COMMENT ON COLUMN public.customers.postal_code IS 'CEP, apenas números';
COMMENT ON COLUMN public.customers.street IS 'Nome da rua';
COMMENT ON COLUMN public.customers.address_number IS 'Número do endereço';
COMMENT ON COLUMN public.customers.neighborhood IS 'Bairro';
COMMENT ON COLUMN public.customers.city IS 'Cidade';
COMMENT ON COLUMN public.customers.state IS 'Estado, controlado pelo sistema';
COMMENT ON COLUMN public.customers.country IS 'País, padrão BR';

-- Habilitar Row Level Security (Recomendado no Supabase)
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Política de exemplo para permitir acesso público (Ajuste conforme sua necessidade de segurança)
-- CREATE POLICY "Public Access" ON public.customers FOR ALL USING (true);
-- Adicionando coluna para vincular cliente ao executivo
ALTER TABLE public.customers
ADD COLUMN executive_id bigint NULL REFERENCES public.executives(id);

-- Comentário
COMMENT ON COLUMN public.customers.executive_id IS 'Executivo responsável pelo cliente, referencia executives.id';
CREATE INDEX idx_customers_executive_id ON public.customers(executive_id);
-- Criar índice para clientes por executivo
