-- Criação da tabela documents
CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_valid boolean DEFAULT true,
    -- Categoria e tipo do documento (enums)
    category int NOT NULL, -- exemplo: 1=Identidade, 2=Contrato, 3=Comprovante de endereço
    type int NOT NULL,     -- sub-tipo dentro da categoria
    
    -- Arquivo
    file_url text NOT NULL, -- URL do documento armazenado (S3, Supabase Storage, etc)
    
    -- Status do documento
    status int NOT NULL CHECK (status IN (1,2,3)), -- 1=pendente, 2=aprovado, 3=rejeitado

    -- Propriedade (cliente ou executivo)
    owner_id bigint NOT NULL,
    owner_type int NOT NULL CHECK(owner_type IN (1,2)), -- 1=cliente, 2=executivo
    
    -- Timestamps automáticos
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Comentários
COMMENT ON COLUMN public.documents.category IS 'Categoria do documento, controlada pelo sistema';
COMMENT ON COLUMN public.documents.type IS 'Tipo do documento dentro da categoria';
COMMENT ON COLUMN public.documents.file_url IS 'URL do arquivo do documento';
COMMENT ON COLUMN public.documents.status IS 'Status do documento: 1=enviado,2=aprovado,3=rejeitado';
COMMENT ON COLUMN public.documents.owner_id IS 'ID do proprietário do documento (cliente ou executivo)';
COMMENT ON COLUMN public.documents.owner_type IS 'Tipo do proprietário: 1=cliente, 2=executivo';
COMMENT ON COLUMN public.documents.created_at IS 'Data de criação do registro';
COMMENT ON COLUMN public.documents.updated_at IS 'Data da última atualização do registro';
COMMENT ON COLUMN public.documents.is_valid IS 'Indica se o documento é considerado válido pelo sistema';
-- Habilitar Row Level Security
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- Índices recomendados
CREATE INDEX idx_documents_owner ON public.documents(owner_id, owner_type);
CREATE INDEX idx_documents_status ON public.documents(status);
