-- Criação da tabela executives
CREATE TABLE IF NOT EXISTS public.executives (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Tipo de cliente: PF ou PJ
    customer_type char(2) NOT NULL CHECK (customer_type IN ('PF', 'PJ')),
    
    register_date timestamp with time zone DEFAULT timezone('utc'::text, now()),
    
    -- Pessoa Física do executivo (se tiver CPF)
    full_name text,
    cpf varchar(11),
    marital_status int,
    rg varchar(10),
    birth_place text,
    birth_date date,
    email text UNIQUE,
    
    -- Pessoa Jurídica
    company_name text,
    trade_name text,
    cnpj varchar(14),
    representative_name text,
    job_title text,
    
    -- Contato
    phone varchar(15),
    whatsapp varchar(15),
    
    -- Endereço
    postal_code varchar(8),
    street text,
    address_number text,
    complement text,
    neighborhood text,
    city text,
    state int,
    country char(2) DEFAULT 'BR',
    
    -- Restrições (Checks)
    CONSTRAINT executives_cpf_check CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$'),
    CONSTRAINT executives_cnpj_check CHECK (cnpj IS NULL OR cnpj ~ '^[0-9]{14}$'),
    CONSTRAINT executives_phone_check CHECK (phone IS NULL OR phone ~ '^[0-9]{10,13}$'),
    CONSTRAINT executives_whatsapp_check CHECK (whatsapp IS NULL OR whatsapp ~ '^[0-9]{10,13}$'),
    CONSTRAINT executives_postal_code_check CHECK (postal_code IS NULL OR postal_code ~ '^[0-9]{8}$'),
    CONSTRAINT executives_marital_status_check CHECK (marital_status IS NULL OR marital_status IN (1, 2, 3, 4, 5)),
    CONSTRAINT executives_state_check CHECK (state IS NULL OR (state >= 1 AND state <= 27)),
    
    -- Unique opcional (CPF ou CNPJ)
    CONSTRAINT executives_cpf_unique UNIQUE (cpf),
    CONSTRAINT executives_cnpj_unique UNIQUE (cnpj)
);

-- Comentários
COMMENT ON COLUMN public.executives.customer_type IS 'PJ fixo para executives';
COMMENT ON COLUMN public.executives.full_name IS 'Nome completo do executivo';
COMMENT ON COLUMN public.executives.cpf IS 'CPF do executivo, apenas números, único mas opcional';
COMMENT ON COLUMN public.executives.marital_status IS 'Estado civil do executivo, controlado pelo sistema';
COMMENT ON COLUMN public.executives.birth_place IS 'Naturalidade do executivo';
COMMENT ON COLUMN public.executives.birth_date IS 'Data de nascimento do executivo';
COMMENT ON COLUMN public.executives.email IS 'Email do executivo, único';
COMMENT ON COLUMN public.executives.company_name IS 'Razão social da empresa do executivo';
COMMENT ON COLUMN public.executives.trade_name IS 'Nome fantasia da empresa do executivo';
COMMENT ON COLUMN public.executives.cnpj IS 'CNPJ da empresa do executivo, apenas números, único mas opcional';
COMMENT ON COLUMN public.executives.representative_name IS 'Nome do representante da empresa (se houver)';
COMMENT ON COLUMN public.executives.job_title IS 'Cargo ou função do executivo';
COMMENT ON COLUMN public.executives.phone IS 'Telefone fixo ou celular';
COMMENT ON COLUMN public.executives.whatsapp IS 'Número de WhatsApp';
COMMENT ON COLUMN public.executives.postal_code IS 'CEP, apenas números';
COMMENT ON COLUMN public.executives.street IS 'Nome da rua';
COMMENT ON COLUMN public.executives.address_number IS 'Número do endereço';
COMMENT ON COLUMN public.executives.neighborhood IS 'Bairro';
COMMENT ON COLUMN public.executives.city IS 'Cidade';
COMMENT ON COLUMN public.executives.state IS 'Estado, controlado pelo sistema';
COMMENT ON COLUMN public.executives.country IS 'País, padrão BR';

-- Habilitar Row Level Security
ALTER TABLE public.executives ENABLE ROW LEVEL SECURITY;

-- Política de exemplo para permitir acesso público (ajustar conforme segurança)
CREATE POLICY "Public Access" ON public.executives FOR ALL USING (true);
-- Adicionando coluna para vincular cliente ao executivo
-- Adicionando coluna para vincular líder do executivo
ALTER TABLE public.executives
ADD COLUMN leader_id bigint NULL REFERENCES public.executives(id);

-- Comentário
COMMENT ON COLUMN public.executives.leader_id IS 'Executivo líder (manager) deste executivo, referência autorreferencial para executives.id';
-- Criar índice para o campo leader_id
CREATE INDEX idx_executives_leader_id
ON public.executives(leader_id);

-- Adicionando campo role na tabela executives
ALTER TABLE public.executives
ADD COLUMN role int NOT NULL DEFAULT 2
    CONSTRAINT executives_role_check CHECK (role IN (0,1,2,3));

-- Comentário explicativo
COMMENT ON COLUMN public.executives.role IS 'Role do executivo: 0=HEAD, 1=LEADER, 2=EXECUTIVE, 3=FINANCEIRO';
